import turtle
import numpy as np
def s(r):
    for i in range(0,36):
        turtle.forward(2*np.pi*(r)/360)
        turtle.left(10)
def d(r):
    for i in range(0,18):
        turtle.forward(2*np.pi*(r)/360)
        turtle.right(10)
turtle.shape('turtle')
turtle.speed(10)
turtle.goto(0,0)
turtle.left(90)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.left(90)
turtle.begin_fill()
turtle.color('yellow')
s(1000)
turtle.end_fill()
turtle.goto(-50,50)
turtle.begin_fill()
turtle.color('blue')
s(100)
turtle.end_fill()
turtle.penup()
turtle.goto(30,50)
turtle.pendown()
turtle.begin_fill()
turtle.color('blue')
s(100)
turtle.end_fill()
turtle.color('black')
turtle.width(10)
turtle.penup()
turtle.goto(-10,15)
turtle.left(90)
turtle.pendown()
turtle.forward(30)
turtle.penup()
turtle.goto(35,-30)
turtle.pendown()
turtle.color('red')
d(450)

